#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("DialogSampleApp.Resource", IsApplication=true)]

namespace DialogSampleApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Android.Dialog.Resource.Drawable.dialog_disclosure = global::DialogSampleApp.Resource.Drawable.dialog_disclosure;
			global::Android.Dialog.Resource.Drawable.expander_ic_minimized = global::DialogSampleApp.Resource.Drawable.expander_ic_minimized;
			global::Android.Dialog.Resource.Id.dialog_BoolField = global::DialogSampleApp.Resource.Id.dialog_BoolField;
			global::Android.Dialog.Resource.Id.dialog_Button = global::DialogSampleApp.Resource.Id.dialog_Button;
			global::Android.Dialog.Resource.Id.dialog_DisclosureField = global::DialogSampleApp.Resource.Id.dialog_DisclosureField;
			global::Android.Dialog.Resource.Id.dialog_HtmlField = global::DialogSampleApp.Resource.Id.dialog_HtmlField;
			global::Android.Dialog.Resource.Id.dialog_ImageLeft = global::DialogSampleApp.Resource.Id.dialog_ImageLeft;
			global::Android.Dialog.Resource.Id.dialog_ImageRight = global::DialogSampleApp.Resource.Id.dialog_ImageRight;
			global::Android.Dialog.Resource.Id.dialog_LabelField = global::DialogSampleApp.Resource.Id.dialog_LabelField;
			global::Android.Dialog.Resource.Id.dialog_LabelPercentageField = global::DialogSampleApp.Resource.Id.dialog_LabelPercentageField;
			global::Android.Dialog.Resource.Id.dialog_LabelSubtextField = global::DialogSampleApp.Resource.Id.dialog_LabelSubtextField;
			global::Android.Dialog.Resource.Id.dialog_Panel = global::DialogSampleApp.Resource.Id.dialog_Panel;
			global::Android.Dialog.Resource.Id.dialog_RadioButtonList = global::DialogSampleApp.Resource.Id.dialog_RadioButtonList;
			global::Android.Dialog.Resource.Id.dialog_SliderField = global::DialogSampleApp.Resource.Id.dialog_SliderField;
			global::Android.Dialog.Resource.Id.dialog_Spinner = global::DialogSampleApp.Resource.Id.dialog_Spinner;
			global::Android.Dialog.Resource.Id.dialog_ValueField = global::DialogSampleApp.Resource.Id.dialog_ValueField;
			global::Android.Dialog.Resource.Layout.dialog_achievements = global::DialogSampleApp.Resource.Layout.dialog_achievements;
			global::Android.Dialog.Resource.Layout.dialog_boolfieldleft = global::DialogSampleApp.Resource.Layout.dialog_boolfieldleft;
			global::Android.Dialog.Resource.Layout.dialog_boolfieldright = global::DialogSampleApp.Resource.Layout.dialog_boolfieldright;
			global::Android.Dialog.Resource.Layout.dialog_boolfieldsubleft = global::DialogSampleApp.Resource.Layout.dialog_boolfieldsubleft;
			global::Android.Dialog.Resource.Layout.dialog_boolfieldsubright = global::DialogSampleApp.Resource.Layout.dialog_boolfieldsubright;
			global::Android.Dialog.Resource.Layout.dialog_button = global::DialogSampleApp.Resource.Layout.dialog_button;
			global::Android.Dialog.Resource.Layout.dialog_datefield = global::DialogSampleApp.Resource.Layout.dialog_datefield;
			global::Android.Dialog.Resource.Layout.dialog_fieldsetlabel = global::DialogSampleApp.Resource.Layout.dialog_fieldsetlabel;
			global::Android.Dialog.Resource.Layout.dialog_floatimage = global::DialogSampleApp.Resource.Layout.dialog_floatimage;
			global::Android.Dialog.Resource.Layout.dialog_html = global::DialogSampleApp.Resource.Layout.dialog_html;
			global::Android.Dialog.Resource.Layout.dialog_labelfieldbelow = global::DialogSampleApp.Resource.Layout.dialog_labelfieldbelow;
			global::Android.Dialog.Resource.Layout.dialog_labelfieldright = global::DialogSampleApp.Resource.Layout.dialog_labelfieldright;
			global::Android.Dialog.Resource.Layout.dialog_multiline_labelfieldbelow = global::DialogSampleApp.Resource.Layout.dialog_multiline_labelfieldbelow;
			global::Android.Dialog.Resource.Layout.dialog_onofffieldright = global::DialogSampleApp.Resource.Layout.dialog_onofffieldright;
			global::Android.Dialog.Resource.Layout.dialog_panel = global::DialogSampleApp.Resource.Layout.dialog_panel;
			global::Android.Dialog.Resource.Layout.dialog_root = global::DialogSampleApp.Resource.Layout.dialog_root;
			global::Android.Dialog.Resource.Layout.dialog_selectlist = global::DialogSampleApp.Resource.Layout.dialog_selectlist;
			global::Android.Dialog.Resource.Layout.dialog_selectlistfield = global::DialogSampleApp.Resource.Layout.dialog_selectlistfield;
			global::Android.Dialog.Resource.Layout.dialog_textarea = global::DialogSampleApp.Resource.Layout.dialog_textarea;
			global::Android.Dialog.Resource.Layout.dialog_textfieldbelow = global::DialogSampleApp.Resource.Layout.dialog_textfieldbelow;
			global::Android.Dialog.Resource.Layout.dialog_textfieldright = global::DialogSampleApp.Resource.Layout.dialog_textfieldright;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int dialog_disclosure = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int dialog_expander_ic_minimized = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int expander_ic_minimized = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int monoandroidsplash = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060004
			public const int dialog_BoolField = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int dialog_Button = 2131099653;
			
			// aapt resource value: 0x7f06000b
			public const int dialog_DisclosureField = 2131099659;
			
			// aapt resource value: 0x7f060009
			public const int dialog_HtmlField = 2131099657;
			
			// aapt resource value: 0x7f060007
			public const int dialog_ImageLeft = 2131099655;
			
			// aapt resource value: 0x7f060002
			public const int dialog_ImageRight = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int dialog_LabelField = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int dialog_LabelPercentageField = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int dialog_LabelSubtextField = 2131099649;
			
			// aapt resource value: 0x7f06000a
			public const int dialog_Panel = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int dialog_RadioButtonList = 2131099660;
			
			// aapt resource value: 0x7f060008
			public const int dialog_SliderField = 2131099656;
			
			// aapt resource value: 0x7f06000d
			public const int dialog_Spinner = 2131099661;
			
			// aapt resource value: 0x7f060006
			public const int dialog_ValueField = 2131099654;
			
			// aapt resource value: 0x7f06000e
			public const int iFormFieldValue = 2131099662;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int dialog_achievements = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int dialog_boolfieldleft = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int dialog_boolfieldright = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int dialog_boolfieldsubleft = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int dialog_boolfieldsubright = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int dialog_button = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int dialog_datefield = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int dialog_fieldsetlabel = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int dialog_floatimage = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int dialog_html = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int dialog_labelfieldbelow = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int dialog_labelfieldright = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int dialog_multiline_labelfieldbelow = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int dialog_onofffieldright = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int dialog_panel = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int dialog_root = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int dialog_selectlist = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int dialog_selectlistfield = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int dialog_textarea = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int dialog_textfieldbelow = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int dialog_textfieldright = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int main = 2130903061;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
